### ISSUE TITLE
Integration of improvements added to the library by the OpenPGP.js project

### ISSUE THREAD

**Issue by evilaliv3** [andyperlitch/jsbn#12]
A lot of improvements to the library and it's packaging have been implemented by the OpenPGP.js team during time.

It would be great to start integrating the various fixes to jsbn that opensource sofware have produced during time.
https://github.com/openpgpjs/openpgpjs/blob/ad920c6eb0e0f3d3d20170270791853bc478fdcc/src/crypto/public_key/jsbn.js

E.g. it would be nice to integrate fixes like by first assessing if the performances improvements exists or are fake :)
- https://github.com/openpgpjs/openpgpjs/issues/106
- https://github.com/openpgpjs/openpgpjs/pull/415

**Comment by andyperlitch** [comment]
I know its late, but thanks for the heads up. I'll run some tests and integrate that change if it checks out.
