### ISSUE TITLE
Release Confusion

### ISSUE THREAD

**Issue by grempe** [andyperlitch/jsbn#14]
Hi,

I am a little confused as to what is happening with the releases for jsbn.
## v0.1.0

Is the latest release on npmjs:

https://www.npmjs.com/package/jsbn

This release is not easy to validate and determine what it contains on Github since it was apparently cut from an orphaned branch that no longer exists. The branch that it was tagged from also contains another commit with a license change that is not on master. Here is a screenshot of its history from Gitup.

<img width="226" alt="jsbn_branch" src="https://cloud.githubusercontent.com/assets/117/15381333/a0eb5a04-1d33-11e6-85ea-8aad1475692c.png">
## v1.0.0

Is the latest release on the releases page on Github, cut off of the master branch about 2 months ago.  However, this release has not been pushed to npmjs.

It would be great if you could clarify if v1.0.0 is the current release that should be used, and if so please push it to npmjs.

Thanks!

**Comment by sandersiim** [comment]
+1 for updating the package version in npm repository to v.1.0.0.

The current version in npm repository incorrectly exports the interface in browser environment, which was fixed in commit https://github.com/andyperlitch/jsbn/commit/2a01ba3a0714085959aa458e791f7383263e925d.

**Comment by andyperlitch** [comment]
Sorry for the lag. I am doing some clean-ups now and will be publishing 1.0.0 very soon.

**Comment by andyperlitch** [comment]
Ok, I have released two new versions and published to npm.

- `v0.1.1` fixes a backwards-incompatible change from `v0.0.0`, but is still compatible with `v0.1.0` usage (`require('jsbn').BigInteger` is still valid).

- `v1.0.0` was already there, just not published to npm
- `v1.1.0` registered `BigInteger` as the "default import" for es6.

I also added a changelog to keep track of these changes.

**Comment by sandersiim** [comment]
Great, thanks for clearing it up!

**Comment by grempe** [comment]
Thanks for the updates and the releases. Glad to see this issue finally addressed (and at 9 million downloads per month I'm sure I'm not the only one!).
