### ISSUE TITLE
Clarify license: MIT or BSD?

### ISSUE THREAD

**Issue by goloroden** [andyperlitch/jsbn#17]
In `package.json` it says that this module is released under the BSD license. But the text in the `LICENSE` file looks more like the MIT license. Which one is right? And, just in case, that it is actually BSD, is it 2-, 3-, or 4-clause BSD?

It would be great if you could clarify this, and update the `package.json` file to contain a valid SPDX expression, such as `MIT` or `BSD-2-Clause`, for example.

**Comment by andyperlitch** [comment]
I got the license text from [Tom Wu's original site](http://www-cs-students.stanford.edu/~tjw/jsbn/LICENSE). I believe i put bsd in error and will change it to MIT.

**Comment by goloroden** [comment]
Great, thanks a lot 😊

**Comment by andyperlitch** [comment]
It has been changed as of v1.1.0. Again, thanks for the heads-up!
