### ISSUE TITLE
Can jsbn run on ES5?

### ISSUE THREAD

**Issue by cam510** [andyperlitch/jsbn#30]
hello,
The project can run when I babel + webpack output es5,
when i output es5,run on android 6 error,
the error is Cannot assign to read only property 'window' of object '#'Window

**Comment by andyperlitch** [comment]
Hmm i imagine it is because the library attempts to add some globals to the window object. It checks if `exports` exists and if it does not, it assigns `jsbn` to the window object. I’m not familiar with androids js environment, best of luck.

**Comment by cam510** [comment]
@andyperlitch thanks
maybe some errors when I config the webpack
